#!/bin/bash

echo "🧹 Limpando escolha de métricas anônimas..."
echo ""
echo "Para limpar sua escolha de métricas e ver o modal novamente:"
echo ""
echo "1. Abra o navegador em: http://localhost:5176/"
echo ""
echo "2. Abra o DevTools (F12)"
echo ""
echo "3. Vá para a aba 'Application' (Chrome) ou 'Storage' (Firefox)"
echo ""
echo "4. No menu lateral, clique em 'Local Storage'"
echo ""
echo "5. Clique em 'http://localhost:5176'"
echo ""
echo "6. Procure pela chave 'citrineos-telemetry-consent'"
echo ""
echo "7. Clique com o botão direito na chave e selecione 'Delete'"
echo ""
echo "8. Atualize a página (F5)"
echo ""
echo "9. O modal 'Anonymous Metrics Consent' deve aparecer novamente"
echo ""
echo "💡 Alternativa via Console:"
echo "   - Abra o Console (F12 → Console)"
echo "   - Digite: localStorage.removeItem('citrineos-telemetry-consent')"
echo "   - Pressione Enter"
echo "   - Atualize a página"
echo ""
echo "🎯 Isso permitirá testar a funcionalidade novamente!"
