#!/bin/bash

echo "🔍 Debugando problema dos campos de latitude e longitude..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste de Debug dos Campos de Coordenadas:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "5. Teste os campos passo a passo:"
echo ""
echo "   📍 TESTE 1 - Campo Latitude:"
echo "   - Digite: -23.5505"
echo "   - Observe no console se há erros"
echo "   - Clique fora do campo"
echo "   - Verifique se o valor permanece: -23.5505"
echo ""
echo "   📍 TESTE 2 - Campo Longitude:"
echo "   - Digite: -46.6333"
echo "   - Observe no console se há erros"
echo "   - Clique fora do campo"
echo "   - Verifique se o valor permanece: -46.6333"
echo ""
echo "   📍 TESTE 3 - Campo Vazio:"
echo "   - Deixe o campo vazio"
echo "   - Clique fora do campo"
echo "   - Verifique se não aparece 0"
echo ""
echo "   📍 TESTE 4 - Valor 0:"
echo "   - Digite: 0"
echo "   - Clique fora do campo"
echo "   - Verifique se o valor 0 é mantido (não deve ser alterado)"
echo ""
echo "6. Se ainda houver problemas, verifique:"
echo "   - Console do navegador para erros JavaScript"
echo "   - Network tab para requisições falhando"
echo "   - Se o servidor está rodando corretamente"
echo ""
echo "🔧 Correções aplicadas:"
echo "   - Removido onBlur handler problemático"
echo "   - Adicionado validação lat !== 0 e lng !== 0"
echo "   - Mantido precision={6} e step={0.000001}"
echo "   - Simplificado a lógica de onChange"
echo ""
echo "📍 Coordenadas de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "💡 Se o problema persistir, me informe:"
echo "   - Qual valor você digitou"
echo "   - O que aconteceu quando clicou fora"
echo "   - Se há erros no console do navegador"
