#!/bin/bash

echo "🔍 Debugando marcadores do mapa..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Debug dos Marcadores do Mapa:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para a Home (página inicial)"
echo ""
echo "4. Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "5. Verifique se há erros no console relacionados ao mapa"
echo ""
echo "6. Vá para: Locations → Map"
echo ""
echo "7. Verifique se:"
echo "   - O mapa carrega corretamente"
echo "   - Há marcadores visíveis"
echo "   - Não há erros no console"
echo ""
echo "8. Vá para: Locations → Editar uma localização existente"
echo ""
echo "9. Verifique se:"
echo "   - O mapa mostra as coordenadas atuais"
echo "   - Há um marcador na localização"
echo "   - Os campos de latitude/longitude estão preenchidos"
echo ""
echo "🔧 Possíveis Problemas:"
echo "   - API key do Google Maps inválida"
echo "   - Estrutura de coordenadas incorreta"
echo "   - Marcadores não sendo renderizados"
echo "   - Problemas de sincronização"
echo ""
echo "📍 Informações para Debug:"
echo "   - API Key: AIzaSyBp8EbkA88gKWO8RHApudo9eoVJXhAztBk"
echo "   - Coordenadas esperadas: [longitude, latitude]"
echo "   - Marcadores devem aparecer em todas as localizações"
echo ""
echo "💡 Se houver problemas, me informe:"
echo "   - Erros no console do navegador"
echo "   - Se o mapa carrega mas não mostra marcadores"
echo "   - Se há localizações cadastradas"
echo "   - Se a API key está funcionando"
