#!/bin/bash

echo "🧪 Testando correção dos erros do console..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste da Correção dos Erros do Console:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "4. Navegue pela aplicação e verifique se:"
echo ""
echo "   ✅ NÃO aparece mais: 'GET http://localhost:5176/config.js net::ERR_ABORTED 404'"
echo "   ✅ NÃO aparece mais: 'Warning: Each child in a list should have a unique key prop'"
echo "   ✅ NÃO aparece mais: 'O mapa é inicializado sem um ID de mapa válido'"
echo ""
echo "5. Teste específico - Vá para: Locations → [Qualquer localização] → View Details"
echo ""
echo "6. Verifique se:"
echo "   - ✅ A página carrega sem erros"
echo "   - ✅ As facilities são exibidas corretamente (se houver)"
echo "   - ✅ NÃO há warnings sobre 'key' prop no console"
echo ""
echo "7. Teste o mapa:"
echo "   - Vá para: Locations → Map"
echo "   - ✅ Mapa carrega sem erros"
echo "   - ✅ Marcadores aparecem (se houver localizações)"
echo ""
echo "🔧 Correções Aplicadas:"
echo "   - Criado arquivo public/config.js para resolver erro 404"
echo "   - Adicionado key prop no map de facilities"
echo "   - Configurações dinâmicas funcionando"
echo "   - Mapa com IDs válidos"
echo ""
echo "📍 Arquivos Modificados:"
echo "   - public/config.js (criado)"
echo "   - src/pages/locations/detail/location.detail.card.tsx (corrigido)"
echo ""
echo "🎉 Se não houver mais erros no console, as correções funcionaram!"
echo ""
echo "💡 Estas correções resolvem:"
echo "   - Erro 404 do config.js"
echo "   - Warning de key prop no React"
echo "   - Configurações dinâmicas"
echo "   - Melhor experiência de desenvolvimento"
