#!/bin/bash

echo "🧪 Testando correção do ID do mapa..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste da Correção do ID do Mapa:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Abra o DevTools (F12) e vá para a aba Console"
echo ""
echo "4. Vá para: Locations → Map"
echo ""
echo "5. Verifique se:"
echo "   - ✅ NÃO aparece mais o erro: 'O mapa é inicializado sem um ID de mapa válido'"
echo "   - ✅ O mapa carrega corretamente"
echo "   - ✅ Os marcadores aparecem (se houver localizações)"
echo ""
echo "6. Vá para: Locations → Create Location"
echo ""
echo "7. Verifique se:"
echo "   - ✅ O mapa do seletor de localização carrega"
echo "   - ✅ NÃO há erros no console"
echo "   - ✅ É possível clicar no mapa para selecionar localização"
echo ""
echo "8. Vá para: Locations → Editar uma localização existente"
echo ""
echo "9. Verifique se:"
echo "   - ✅ O mapa mostra as coordenadas atuais"
echo "   - ✅ NÃO há erros no console"
echo "   - ✅ Os campos de latitude/longitude estão preenchidos"
echo ""
echo "🔧 Correções Aplicadas:"
echo "   - Adicionado Map IDs no arquivo .env"
echo "   - Modificado código para usar mapId apenas se estiver definido"
echo "   - Fallback para mapas sem ID específico"
echo "   - Prevenção de erros de inicialização"
echo ""
echo "📍 Configurações Adicionadas:"
echo "   - VITE_GOOGLE_MAPS_LOCATION_PICKER_MAP_ID=citrineos-location-picker"
echo "   - VITE_GOOGLE_MAPS_OVERVIEW_MAP_ID=citrineos-overview"
echo ""
echo "🎉 Se não houver mais erros no console, a correção funcionou!"
echo ""
echo "💡 Esta correção resolve:"
echo "   - Erro de ID de mapa inválido"
echo "   - Problemas com marcadores avançados"
echo "   - Inicialização correta dos mapas"
echo "   - Fallback para mapas sem ID específico"
