#!/bin/bash

echo "🧪 Testando correção do problema de colar coordenadas..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste Específico - Colar Coordenadas:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - O campo deve mostrar: 0.000000"
echo "   - Clique no campo"
echo "   - Cole o valor: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - O campo deve mostrar: 0.000000"
echo "   - Clique no campo"
echo "   - Cole o valor: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo ""
echo "6. Teste com outros valores:"
echo "   - Latitude: -22.9068 (Rio de Janeiro)"
echo "   - Longitude: -43.1729 (Rio de Janeiro)"
echo "   - Verifique se ambos permanecem após clicar fora"
echo ""
echo "🔧 Correção aplicada:"
echo "   - Removido a condição 'lat !== 0' e 'lng !== 0'"
echo "   - Agora aceita qualquer valor válido (incluindo 0)"
echo "   - Mantido validação para null e NaN"
echo "   - Precisão de 6 casas decimais mantida"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se os valores colados permanecerem após clicar fora, a correção funcionou!"
echo ""
echo "💡 Se ainda não funcionar, me informe:"
echo "   - Qual valor você colou"
echo "   - O que aconteceu quando clicou fora"
echo "   - Se há erros no console do navegador"
