#!/bin/bash

echo "🧪 Testando correção do problema de colagem..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste da Correção de Colagem:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - Cole: -23.5505"
echo "   - ✅ Verifique se o valor aparece: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - Cole: -46.85005"
echo "   - ✅ Verifique se o valor aparece: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo ""
echo "6. Teste digitação:"
echo "   - Digite: -22.9068 no campo Latitude"
echo "   - Digite: -43.1729 no campo Longitude"
echo "   - Clique fora de ambos os campos"
echo "   - ✅ Verifique se os valores são mantidos"
echo ""
echo "7. Teste com valores positivos:"
echo "   - Cole: 23.5505 no campo Latitude"
echo "   - Cole: 46.85005 no campo Longitude"
echo "   - ✅ Verifique se os valores são mantidos"
echo ""
echo "8. Teste com o mapa:"
echo "   - Clique em um ponto no mapa"
echo "   - ✅ Verifique se os campos são atualizados"
echo ""
echo "🔧 Correção Aplicada:"
echo "   - onChange: Permite entrada de texto livre"
echo "   - onBlur: Valida e converte para número"
echo "   - Sem validação restritiva durante digitação"
echo "   - Validação apenas quando perde o foco"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se a colagem funcionar corretamente, a correção funcionou!"
echo ""
echo "💡 Esta correção permite:"
echo "   - Colagem livre de valores"
echo "   - Digitação sem restrições"
echo "   - Validação apenas no onBlur"
echo "   - Conversão para número quando necessário"
