#!/bin/bash

echo "🧪 Testando correção dos campos de latitude e longitude..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste de Foco dos Campos de Coordenadas:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location ou Edit Location"
echo ""
echo "4. Teste os campos de coordenadas:"
echo "   - Digite uma latitude válida: -23.5505"
echo "   - Clique fora do campo (perde o foco)"
echo "   - Verifique se o valor permanece: -23.5505"
echo ""
echo "   - Digite uma longitude válida: -46.6333"
echo "   - Clique fora do campo (perde o foco)"
echo "   - Verifique se o valor permanece: -46.6333"
echo ""
echo "5. Teste casos especiais:"
echo "   - Deixe o campo vazio e clique fora"
echo "   - Digite 0 e clique fora"
echo "   - Digite texto inválido e clique fora"
echo ""
echo "6. Verifique se:"
echo "   ✅ Valores válidos são mantidos ao perder foco"
echo "   ✅ Valores inválidos não são convertidos para 0"
echo   "   ✅ Campos vazios não são preenchidos com 0"
echo "   ✅ Precisão de 6 casas decimais é mantida"
echo ""
echo "🔧 Correções aplicadas:"
echo "   - Adicionado onBlur handler para validação"
echo "   - Adicionado precision={6} para 6 casas decimais"
echo "   - Adicionado step={0.000001} para incrementos precisos"
echo "   - Validação para evitar valores 0 inválidos"
echo ""
echo "📍 Coordenadas de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se os valores não mudarem para 0 ao perder foco, a correção funcionou!"
