#!/bin/bash

echo "🧪 Teste Final - Campos de Latitude e Longitude Corrigidos..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste Final dos Campos de Coordenadas:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - Digite: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - Digite: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo ""
echo "6. Teste colando valores:"
echo "   - Cole: -22.9068 no campo Latitude"
echo "   - Cole: -43.1729 no campo Longitude"
echo "   - Clique fora de ambos os campos"
echo "   - ✅ Verifique se ambos os valores permanecem"
echo ""
echo "7. Teste com o mapa:"
echo "   - Clique em um ponto no mapa"
echo "   - ✅ Verifique se os campos são atualizados"
echo ""
echo "8. Teste de submissão:"
echo "   - Preencha outros campos obrigatórios"
echo "   - Clique em Submit"
echo "   - ✅ Verifique se a localização é criada com as coordenadas corretas"
echo ""
echo "🔧 Correções Aplicadas:"
echo "   - Estados locais para latitude e longitude"
echo "   - Ordem correta das coordenadas: [longitude, latitude]"
echo "   - onBlur handler para persistir valores"
echo "   - Sincronização com formulário e mapa"
echo "   - Precisão de 6 casas decimais"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se todos os testes passarem, os campos estão funcionando corretamente!"
echo ""
echo "💡 Esta solução usa:"
echo "   - Estados locais para controle direto dos valores"
echo "   - onBlur para garantir persistência"
echo "   - Sincronização bidirecional com formulário e mapa"
echo "   - Ordem correta das coordenadas GeoJSON"
