#!/bin/bash

echo "🧪 Testando sincronização final do mapa com coordenadas..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste de Sincronização do Mapa:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste sincronização Campos → Mapa:"
echo "   - Digite: -23.5505 no campo Latitude"
echo "   - Digite: -46.6333 no campo Longitude"
echo "   - Clique fora dos campos"
echo "   - ✅ Verifique se o mapa mostra um marcador em São Paulo"
echo "   - ✅ Verifique se o mapa centraliza na localização"
echo ""
echo "5. Teste sincronização Mapa → Campos:"
echo "   - Clique em um ponto diferente no mapa"
echo "   - ✅ Verifique se os campos são atualizados"
echo "   - ✅ Verifique se os valores correspondem ao ponto clicado"
echo ""
echo "6. Teste com valores do Rio de Janeiro:"
echo "   - Digite: -22.9068 no campo Latitude"
echo "   - Digite: -43.1729 no campo Longitude"
echo "   - Clique fora dos campos"
echo "   - ✅ Verifique se o mapa mostra um marcador no Rio de Janeiro"
echo ""
echo "7. Teste com valores de Brasília:"
echo "   - Digite: -15.7801 no campo Latitude"
echo "   - Digite: -47.9292 no campo Longitude"
echo "   - Clique fora dos campos"
echo "   - ✅ Verifique se o mapa mostra um marcador em Brasília"
echo ""
echo "🔧 Correção Aplicada:"
echo "   - Criado GeoPoint com new GeoPoint(latitude, longitude)"
echo "   - Sincronização bidirecional: Campos ↔ Mapa"
echo "   - Marcador no mapa reflete coordenadas dos campos"
echo "   - Clique no mapa atualiza os campos"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se o mapa mostrar marcadores nas localizações corretas, a sincronização funcionou!"
echo ""
echo "💡 Esta correção resolve:"
echo "   - Mapa não refletindo coordenadas dos campos"
echo "   - Sincronização bidirecional"
echo "   - Marcadores no mapa"
echo "   - Centralização do mapa nas coordenadas"
