#!/bin/bash

echo "🧪 Testando solução com Input comum para coordenadas..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste da Solução com Input Comum:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - Campo deve estar vazio"
echo "   - Digite: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - Campo deve estar vazio"
echo "   - Digite: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo ""
echo "6. Teste colando valores (PROBLEMA ANTERIOR):"
echo "   - Cole: -22.9068 no campo Latitude"
echo "   - ✅ Verifique se NÃO aparece 0 no início"
echo "   - ✅ Verifique se o valor colado é: -22.9068"
echo "   - Cole: -43.1729 no campo Longitude"
echo "   - ✅ Verifique se NÃO aparece 0 no início"
echo "   - ✅ Verifique se o valor colado é: -43.1729"
echo ""
echo "7. Teste com valores positivos:"
echo "   - Digite: 23.5505 no campo Latitude"
echo "   - Digite: 46.85005 no campo Longitude"
echo "   - ✅ Verifique se os valores são mantidos"
echo ""
echo "8. Teste com o mapa:"
echo "   - Clique em um ponto no mapa"
echo "   - ✅ Verifique se os campos são atualizados"
echo ""
echo "🔧 Nova Solução Implementada:"
echo "   - Substituído InputNumber por Input comum"
echo "   - Controle manual da validação numérica"
echo "   - Sem problemas de colagem"
echo "   - Estados locais para controle direto"
echo "   - Sincronização com formulário e mapa"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se a colagem funcionar sem o 0 fixo, a solução funcionou!"
echo ""
echo "💡 Esta solução resolve:"
echo "   - Problema do 0 fixo no início"
echo "   - Problemas de colagem"
echo "   - Controle total sobre a entrada de dados"
echo "   - Validação numérica manual"
