#!/bin/bash

echo "🧪 Testando sincronização com o mapa..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste de Sincronização com o Mapa:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - Cole: -23.5505"
echo "   - ✅ Verifique se o valor aparece: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo "   - ✅ Verifique se o mapa NÃO interfere com o valor"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - Cole: -46.85005"
echo "   - ✅ Verifique se o valor aparece: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo "   - ✅ Verifique se o mapa NÃO interfere com o valor"
echo ""
echo "6. Teste com o mapa:"
echo "   - Clique em um ponto no mapa"
echo "   - ✅ Verifique se os campos são atualizados corretamente"
echo "   - ✅ Verifique se os valores não voltam para 0"
echo ""
echo "7. Teste de interferência:"
echo "   - Digite valores nos campos"
echo "   - Clique no mapa"
echo "   - ✅ Verifique se os valores dos campos são atualizados"
echo "   - ✅ Verifique se não há conflito entre mapa e campos"
echo ""
echo "🔧 Correção Aplicada:"
echo "   - Mapa usa estados locais quando disponíveis"
echo "   - Fallback para valores do formulário"
echo "   - Sincronização bidirecional melhorada"
echo "   - Prevenção de interferência do mapa"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se o mapa não interferir mais com os valores dos campos, a correção funcionou!"
echo ""
echo "💡 Esta correção resolve:"
echo "   - Interferência do mapa com os campos"
echo "   - Valores voltando para 0"
echo "   - Sincronização bidirecional"
echo "   - Conflitos entre entrada manual e mapa"
