#!/bin/bash

echo "🧪 Testando nova abordagem com estados locais para coordenadas..."
echo ""

# Verificar se o servidor está rodando
echo "🔍 Verificando se o servidor está rodando..."
if curl -s http://localhost:5176/ > /dev/null; then
    echo "✅ Servidor Operator UI está rodando em http://localhost:5176/"
else
    echo "❌ Servidor Operator UI não está rodando"
    echo "💡 Execute: cd citrineos-operator-ui && npm run dev"
    exit 1
fi

echo ""
echo "🎯 Teste da Nova Abordagem - Estados Locais:"
echo ""
echo "1. Acesse: http://localhost:5176/"
echo "2. Faça login com:"
echo "   - Email: admin@citrineos.com"
echo "   - Senha: CitrineOS!"
echo ""
echo "3. Vá para: Locations → Create Location"
echo ""
echo "4. Teste o campo Latitude:"
echo "   - O campo deve estar vazio inicialmente"
echo "   - Digite ou cole: -23.5505"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -23.5505"
echo ""
echo "5. Teste o campo Longitude:"
echo "   - O campo deve estar vazio inicialmente"
echo "   - Digite ou cole: -46.85005"
echo "   - Clique fora do campo"
echo "   - ✅ Verifique se o valor permanece: -46.85005"
echo ""
echo "6. Teste a sincronização:"
echo "   - Altere a latitude para: -22.9068"
echo "   - Altere a longitude para: -43.1729"
echo "   - Clique fora de ambos os campos"
echo "   - ✅ Verifique se ambos os valores permanecem"
echo ""
echo "7. Teste com o mapa:"
echo "   - Clique em um ponto no mapa"
echo "   - ✅ Verifique se os campos são atualizados automaticamente"
echo ""
echo "🔧 Nova Abordagem Implementada:"
echo "   - Estados locais: latitude e longitude"
echo "   - Controle direto dos valores dos campos"
echo "   - Sincronização com o formulário"
echo "   - Sincronização com o mapa"
echo "   - Precisão de 6 casas decimais"
echo ""
echo "📍 Valores de teste:"
echo "   - São Paulo: Lat: -23.5505, Lng: -46.6333"
echo "   - Rio de Janeiro: Lat: -22.9068, Lng: -43.1729"
echo "   - Brasília: Lat: -15.7801, Lng: -47.9292"
echo ""
echo "🎉 Se os valores permanecerem após clicar fora, a nova abordagem funcionou!"
echo ""
echo "💡 Esta abordagem usa estados locais para controlar diretamente"
echo "   os valores dos campos, evitando problemas de sincronização."
